// Voiceline Call Protocol (VCP) — version 1.
//
// VCP lets caller applications (the web phone, vcpc) use a Voiceline line that is
// registered against a SIP provider to place real outbound calls: the client
// authenticates with the line id plus the line's randomly generated call
// password, and from then on every message — signalling AND audio — flows
// encrypted over a single WebSocket.
//
// Transport: WebSocket (ws://host:8086/call), binary messages only.
//
//   1. PLAINTEXT handshake (two protobuf messages, no encryption yet):
//        client  -> HelloRequest { version, line_id, client_nonce }
//        server  -> HelloResponse { version, server_nonce }   (error set => close)
//
//   2. KEY SCHEDULE (both sides, no exchange beyond the two nonces):
//        master   = PBKDF2-HMAC-SHA256(password,
//                                       salt = client_nonce || server_nonce,
//                                       iterations = 60000, length = 96)
//        client_write_key = master[ 0:32]     // client -> server AES-256-GCM
//        server_write_key = master[32:64]     // server -> client AES-256-GCM
//        auth_key         = master[64:96]     // HMAC-SHA256 handshake proof
//
//   3. AUTH (first encrypted frame in each direction, sequence 0):
//        client  -> Envelope{ AuthConfirm {
//            proof = HMAC-SHA256(auth_key,
//                       "VCP/1 client|" || line_id || "|" ||
//                       client_nonce || "|" || server_nonce) } }
//        server  -> Envelope{ AuthResult{ ok, error, line } }
//        (ok = false => the server sends Bye and closes)
//
//   4. SESSION: every WebSocket binary message after the handshake is
//        [ 8-byte big-endian sequence ][ AES-256-GCM ciphertext ][ 16-byte tag ]
//      with nonce = 00 00 00 00 || sequence (8-byte big endian). The sequence
//      strictly increases by one per direction; anything else is a protocol
//      error and the connection drops. The decrypted plaintext is exactly one
//      serialized Envelope message.
//
// Audio is PCM16 little-endian, 8000 Hz, mono, 20 ms frames (160 samples =
// 320 bytes per AudioFrame). The server transcodes to the SIP leg's codec
// (G.711 μ-law/A-law). One line can carry many simultaneous calls — calls are
// independent SIP dialogs and never make the line "busy"; the optional
// max_concurrent line limit is the only bound (0 = unlimited).

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v5.29.3
// source: proto/webcall.proto

package webcallpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HelloRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Protocol version the client speaks (currently 1).
	Version uint32 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	// Id of the Voiceline line to call through (as shown in the console).
	LineId string `protobuf:"bytes,2,opt,name=line_id,json=lineId,proto3" json:"line_id,omitempty"`
	// 16 fresh random bytes, unique per connection attempt.
	ClientNonce   []byte `protobuf:"bytes,3,opt,name=client_nonce,json=clientNonce,proto3" json:"client_nonce,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HelloRequest) Reset() {
	*x = HelloRequest{}
	mi := &file_proto_webcall_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelloRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloRequest) ProtoMessage() {}

func (x *HelloRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_webcall_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloRequest.ProtoReflect.Descriptor instead.
func (*HelloRequest) Descriptor() ([]byte, []int) {
	return file_proto_webcall_proto_rawDescGZIP(), []int{0}
}

func (x *HelloRequest) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *HelloRequest) GetLineId() string {
	if x != nil {
		return x.LineId
	}
	return ""
}

func (x *HelloRequest) GetClientNonce() []byte {
	if x != nil {
		return x.ClientNonce
	}
	return nil
}

type HelloResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Protocol version the server picked (currently 1).
	Version uint32 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	// 16 fresh random bytes from the server.
	ServerNonce []byte `protobuf:"bytes,2,opt,name=server_nonce,json=serverNonce,proto3" json:"server_nonce,omitempty"`
	// Non-empty when the handshake cannot proceed (unknown line, no call
	// password set, unsupported version). The server closes right after.
	Error         string `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HelloResponse) Reset() {
	*x = HelloResponse{}
	mi := &file_proto_webcall_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelloResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloResponse) ProtoMessage() {}

func (x *HelloResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_webcall_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloResponse.ProtoReflect.Descriptor instead.
func (*HelloResponse) Descriptor() ([]byte, []int) {
	return file_proto_webcall_proto_rawDescGZIP(), []int{1}
}

func (x *HelloResponse) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *HelloResponse) GetServerNonce() []byte {
	if x != nil {
		return x.ServerNonce
	}
	return nil
}

func (x *HelloResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// Envelope is the plaintext carried by every encrypted frame: exactly one of
// these messages, serialized.
type Envelope struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*Envelope_AuthConfirm
	//	*Envelope_AuthResult
	//	*Envelope_Dial
	//	*Envelope_CallEvent
	//	*Envelope_Hangup
	//	*Envelope_Dtmf
	//	*Envelope_DtmfEvent
	//	*Envelope_MediaStart
	//	*Envelope_Audio
	//	*Envelope_Ping
	//	*Envelope_Pong
	//	*Envelope_Bye
	//	*Envelope_Transfer
	//	*Envelope_TransferEv
	//	*Envelope_ConfInvite
	//	*Envelope_ConfEvent
	//	*Envelope_InboundSub
	//	*Envelope_InboundAck
	//	*Envelope_Incoming
	//	*Envelope_Accept
	//	*Envelope_Reject
	Payload       isEnvelope_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Envelope) Reset() {
	*x = Envelope{}
	mi := &file_proto_webcall_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Envelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Envelope) ProtoMessage() {}

func (x *Envelope) ProtoReflect() protoreflect.Message {
	mi := &file_proto_webcall_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Envelope.ProtoReflect.Descriptor instead.
func (*Envelope) Descriptor() ([]byte, []int) {
	return file_proto_webcall_proto_rawDescGZIP(), []int{2}
}

func (x *Envelope) GetPayload() isEnvelope_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Envelope) GetAuthConfirm() *AuthConfirm {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_AuthConfirm); ok {
			return x.AuthConfirm
		}
	}
	return nil
}

func (x *Envelope) GetAuthResult() *AuthResult {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_AuthResult); ok {
			return x.AuthResult
		}
	}
	return nil
}

func (x *Envelope) GetDial() *DialRequest {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_Dial); ok {
			return x.Dial
		}
	}
	return nil
}

func (x *Envelope) GetCallEvent() *CallEvent {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_CallEvent); ok {
			return x.CallEvent
		}
	}
	return nil
}

func (x *Envelope) GetHangup() *HangupRequest {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_Hangup); ok {
			return x.Hangup
		}
	}
	return nil
}

func (x *Envelope) GetDtmf() *DtmfRequest {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_Dtmf); ok {
			return x.Dtmf
		}
	}
	return nil
}

func (x *Envelope) GetDtmfEvent() *DtmfEvent {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_DtmfEvent); ok {
			return x.DtmfEvent
		}
	}
	return nil
}

func (x *Envelope) GetMediaStart() *MediaStart {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_MediaStart); ok {
			return x.MediaStart
		}
	}
	return nil
}

func (x *Envelope) GetAudio() *AudioFrame {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_Audio); ok {
			return x.Audio
		}
	}
	return nil
}

func (x *Envelope) GetPing() *Ping {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_Ping); ok {
			return x.Ping
		}
	}
	return nil
}

func (x *Envelope) GetPong() *Pong {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_Pong); ok {
			return x.Pong
		}
	}
	return nil
}

func (x *Envelope) GetBye() *Bye {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_Bye); ok {
			return x.Bye
		}
	}
	return nil
}

func (x *Envelope) GetTransfer() *TransferRequest {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_Transfer); ok {
			return x.Transfer
		}
	}
	return nil
}

func (x *Envelope) GetTransferEv() *TransferEvent {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_TransferEv); ok {
			return x.TransferEv
		}
	}
	return nil
}

func (x *Envelope) GetConfInvite() *ConferenceInvite {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_ConfInvite); ok {
			return x.ConfInvite
		}
	}
	return nil
}

func (x *Envelope) GetConfEvent() *ConferenceEvent {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_ConfEvent); ok {
			return x.ConfEvent
		}
	}
	return nil
}

func (x *Envelope) GetInboundSub() *InboundSubscription {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_InboundSub); ok {
			return x.InboundSub
		}
	}
	return nil
}

func (x *Envelope) GetInboundAck() *InboundAck {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_InboundAck); ok {
			return x.InboundAck
		}
	}
	return nil
}

func (x *Envelope) GetIncoming() *IncomingCallEvent {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_Incoming); ok {
			return x.Incoming
		}
	}
	return nil
}

func (x *Envelope) GetAccept() *AcceptRequest {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_Accept); ok {
			return x.Accept
		}
	}
	return nil
}

func (x *Envelope) GetReject() *RejectRequest {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_Reject); ok {
			return x.Reject
		}
	}
	return nil
}

type isEnvelope_Payload interface {
	isEnvelope_Payload()
}

type Envelope_AuthConfirm struct {
	AuthConfirm *AuthConfirm `protobuf:"bytes,10,opt,name=auth_confirm,json=authConfirm,proto3,oneof"`
}

type Envelope_AuthResult struct {
	AuthResult *AuthResult `protobuf:"bytes,11,opt,name=auth_result,json=authResult,proto3,oneof"`
}

type Envelope_Dial struct {
	Dial *DialRequest `protobuf:"bytes,12,opt,name=dial,proto3,oneof"`
}

type Envelope_CallEvent struct {
	CallEvent *CallEvent `protobuf:"bytes,13,opt,name=call_event,json=callEvent,proto3,oneof"`
}

type Envelope_Hangup struct {
	Hangup *HangupRequest `protobuf:"bytes,14,opt,name=hangup,proto3,oneof"`
}

type Envelope_Dtmf struct {
	Dtmf *DtmfRequest `protobuf:"bytes,15,opt,name=dtmf,proto3,oneof"`
}

type Envelope_DtmfEvent struct {
	DtmfEvent *DtmfEvent `protobuf:"bytes,16,opt,name=dtmf_event,json=dtmfEvent,proto3,oneof"`
}

type Envelope_MediaStart struct {
	MediaStart *MediaStart `protobuf:"bytes,17,opt,name=media_start,json=mediaStart,proto3,oneof"`
}

type Envelope_Audio struct {
	Audio *AudioFrame `protobuf:"bytes,18,opt,name=audio,proto3,oneof"`
}

type Envelope_Ping struct {
	Ping *Ping `protobuf:"bytes,19,opt,name=ping,proto3,oneof"`
}

type Envelope_Pong struct {
	Pong *Pong `protobuf:"bytes,20,opt,name=pong,proto3,oneof"`
}

type Envelope_Bye struct {
	Bye *Bye `protobuf:"bytes,21,opt,name=bye,proto3,oneof"`
}

type Envelope_Transfer struct {
	// v1.1 additions (a v1 server MUST ignore unknown oneof members —
	// older clients simply never send these).
	Transfer *TransferRequest `protobuf:"bytes,30,opt,name=transfer,proto3,oneof"`
}

type Envelope_TransferEv struct {
	TransferEv *TransferEvent `protobuf:"bytes,31,opt,name=transfer_ev,json=transferEv,proto3,oneof"`
}

type Envelope_ConfInvite struct {
	ConfInvite *ConferenceInvite `protobuf:"bytes,32,opt,name=conf_invite,json=confInvite,proto3,oneof"`
}

type Envelope_ConfEvent struct {
	ConfEvent *ConferenceEvent `protobuf:"bytes,33,opt,name=conf_event,json=confEvent,proto3,oneof"`
}

type Envelope_InboundSub struct {
	// v1.2 additions — incoming calls delivered to the client (same rule:
	// unknown members are ignored by older peers).
	InboundSub *InboundSubscription `protobuf:"bytes,34,opt,name=inbound_sub,json=inboundSub,proto3,oneof"` // client -> server
}

type Envelope_InboundAck struct {
	InboundAck *InboundAck `protobuf:"bytes,35,opt,name=inbound_ack,json=inboundAck,proto3,oneof"` // server -> client
}

type Envelope_Incoming struct {
	Incoming *IncomingCallEvent `protobuf:"bytes,36,opt,name=incoming,proto3,oneof"` // server -> client
}

type Envelope_Accept struct {
	Accept *AcceptRequest `protobuf:"bytes,37,opt,name=accept,proto3,oneof"` // client -> server
}

type Envelope_Reject struct {
	Reject *RejectRequest `protobuf:"bytes,38,opt,name=reject,proto3,oneof"` // client -> server
}

func (*Envelope_AuthConfirm) isEnvelope_Payload() {}

func (*Envelope_AuthResult) isEnvelope_Payload() {}

func (*Envelope_Dial) isEnvelope_Payload() {}

func (*Envelope_CallEvent) isEnvelope_Payload() {}

func (*Envelope_Hangup) isEnvelope_Payload() {}

func (*Envelope_Dtmf) isEnvelope_Payload() {}

func (*Envelope_DtmfEvent) isEnvelope_Payload() {}

func (*Envelope_MediaStart) isEnvelope_Payload() {}

func (*Envelope_Audio) isEnvelope_Payload() {}

func (*Envelope_Ping) isEnvelope_Payload() {}

func (*Envelope_Pong) isEnvelope_Payload() {}

func (*Envelope_Bye) isEnvelope_Payload() {}

func (*Envelope_Transfer) isEnvelope_Payload() {}

func (*Envelope_TransferEv) isEnvelope_Payload() {}

func (*Envelope_ConfInvite) isEnvelope_Payload() {}

func (*Envelope_ConfEvent) isEnvelope_Payload() {}

func (*Envelope_InboundSub) isEnvelope_Payload() {}

func (*Envelope_InboundAck) isEnvelope_Payload() {}

func (*Envelope_Incoming) isEnvelope_Payload() {}

func (*Envelope_Accept) isEnvelope_Payload() {}

func (*Envelope_Reject) isEnvelope_Payload() {}

// AuthConfirm is the client's encrypted reply proving it knows the line's
// call password.
type AuthConfirm struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// HMAC-SHA256(auth_key, "VCP/1 client|" + line_id + "|" +
	// client_nonce + "|" + server_nonce).
	Proof []byte `protobuf:"bytes,1,opt,name=proof,proto3" json:"proof,omitempty"`
	// Human-friendly caller name (optional, shown to the callee when the
	// provider supports display names).
	DisplayName string `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	// Free-form client identification, e.g. "webcaller/1.0 (chrome/120)".
	UserAgent     string `protobuf:"bytes,3,opt,name=user_agent,json=userAgent,proto3" json:"user_agent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthConfirm) Reset() {
	*x = AuthConfirm{}
	mi := &file_proto_webcall_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthConfirm) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthConfirm) ProtoMessage() {}

func (x *AuthConfirm) ProtoReflect() protoreflect.Message {
	mi := &file_proto_webcall_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthConfirm.ProtoReflect.Descriptor instead.
func (*AuthConfirm) Descriptor() ([]byte, []int) {
	return file_proto_webcall_proto_rawDescGZIP(), []int{3}
}

func (x *AuthConfirm) GetProof() []byte {
	if x != nil {
		return x.Proof
	}
	return nil
}

func (x *AuthConfirm) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *AuthConfirm) GetUserAgent() string {
	if x != nil {
		return x.UserAgent
	}
	return ""
}

// AuthResult concludes the handshake.
type AuthResult struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Ok    bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	// Failure reason when ok is false.
	Error string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	// Snapshot of the line this session is bound to.
	Line          *LineInfo `protobuf:"bytes,3,opt,name=line,proto3" json:"line,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthResult) Reset() {
	*x = AuthResult{}
	mi := &file_proto_webcall_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthResult) ProtoMessage() {}

func (x *AuthResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_webcall_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthResult.ProtoReflect.Descriptor instead.
func (*AuthResult) Descriptor() ([]byte, []int) {
	return file_proto_webcall_proto_rawDescGZIP(), []int{4}
}

func (x *AuthResult) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *AuthResult) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *AuthResult) GetLine() *LineInfo {
	if x != nil {
		return x.Line
	}
	return nil
}

// LineInfo describes the bound line.
type LineInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// SIP user of the line: the number the callee sees as caller id.
	Number      string `protobuf:"bytes,2,opt,name=number,proto3" json:"number,omitempty"`
	DisplayName string `protobuf:"bytes,3,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	// Registration lifecycle: registering / registered / failed / stopped.
	RegState   string `protobuf:"bytes,4,opt,name=reg_state,json=regState,proto3" json:"reg_state,omitempty"`
	Registered bool   `protobuf:"varint,5,opt,name=registered,proto3" json:"registered,omitempty"`
	// Operator view: on_hook (registered, idle), off_hook (registered, call up),
	// disconnected (no registration).
	Hook string `protobuf:"bytes,6,opt,name=hook,proto3" json:"hook,omitempty"`
	// Calls currently active on the line (all sessions combined).
	ActiveCalls uint32 `protobuf:"varint,7,opt,name=active_calls,json=activeCalls,proto3" json:"active_calls,omitempty"`
	// Configured concurrency bound; 0 = unlimited (the default).
	MaxConcurrent uint32 `protobuf:"varint,8,opt,name=max_concurrent,json=maxConcurrent,proto3" json:"max_concurrent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LineInfo) Reset() {
	*x = LineInfo{}
	mi := &file_proto_webcall_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LineInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LineInfo) ProtoMessage() {}

func (x *LineInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_webcall_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LineInfo.ProtoReflect.Descriptor instead.
func (*LineInfo) Descriptor() ([]byte, []int) {
	return file_proto_webcall_proto_rawDescGZIP(), []int{5}
}

func (x *LineInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *LineInfo) GetNumber() string {
	if x != nil {
		return x.Number
	}
	return ""
}

func (x *LineInfo) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *LineInfo) GetRegState() string {
	if x != nil {
		return x.RegState
	}
	return ""
}

func (x *LineInfo) GetRegistered() bool {
	if x != nil {
		return x.Registered
	}
	return false
}

func (x *LineInfo) GetHook() string {
	if x != nil {
		return x.Hook
	}
	return ""
}

func (x *LineInfo) GetActiveCalls() uint32 {
	if x != nil {
		return x.ActiveCalls
	}
	return 0
}

func (x *LineInfo) GetMaxConcurrent() uint32 {
	if x != nil {
		return x.MaxConcurrent
	}
	return 0
}

// DialRequest places an outbound call through the line.
type DialRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Destination: a plain number ("17005554117"), a registered extension
	// ("1001") or a full SIP URI ("sip:user@host").
	To string `protobuf:"bytes,1,opt,name=to,proto3" json:"to,omitempty"`
	// Optional caller-id display-name override for this call.
	DisplayName string `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	// Seconds to wait for an answer (0 = server default, 60).
	TimeoutSec    uint32 `protobuf:"varint,3,opt,name=timeout_sec,json=timeoutSec,proto3" json:"timeout_sec,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DialRequest) Reset() {
	*x = DialRequest{}
	mi := &file_proto_webcall_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DialRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DialRequest) ProtoMessage() {}

func (x *DialRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_webcall_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DialRequest.ProtoReflect.Descriptor instead.
func (*DialRequest) Descriptor() ([]byte, []int) {
	return file_proto_webcall_proto_rawDescGZIP(), []int{6}
}

func (x *DialRequest) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *DialRequest) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *DialRequest) GetTimeoutSec() uint32 {
	if x != nil {
		return x.TimeoutSec
	}
	return 0
}

// CallEvent reports call progress. The first event after a DialRequest is
// always state "dialing" carrying the call_id the client uses for hangup,
// DTMF and audio frames.
type CallEvent struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	CallId string                 `protobuf:"bytes,1,opt,name=call_id,json=callId,proto3" json:"call_id,omitempty"`
	// dialing | ringing | answered | ended | failed
	State string `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`
	// Human-readable detail: SIP response text, end reason, reject cause.
	Detail string `protobuf:"bytes,3,opt,name=detail,proto3" json:"detail,omitempty"`
	// Unix milliseconds when the call was answered (0 until then).
	AnsweredAtMs uint64 `protobuf:"varint,4,opt,name=answered_at_ms,json=answeredAtMs,proto3" json:"answered_at_ms,omitempty"`
	// Duration of the answered phase in milliseconds (ended events).
	DurationMs    uint32 `protobuf:"varint,5,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CallEvent) Reset() {
	*x = CallEvent{}
	mi := &file_proto_webcall_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CallEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallEvent) ProtoMessage() {}

func (x *CallEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_webcall_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallEvent.ProtoReflect.Descriptor instead.
func (*CallEvent) Descriptor() ([]byte, []int) {
	return file_proto_webcall_proto_rawDescGZIP(), []int{7}
}

func (x *CallEvent) GetCallId() string {
	if x != nil {
		return x.CallId
	}
	return ""
}

func (x *CallEvent) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *CallEvent) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

func (x *CallEvent) GetAnsweredAtMs() uint64 {
	if x != nil {
		return x.AnsweredAtMs
	}
	return 0
}

func (x *CallEvent) GetDurationMs() uint32 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

type HangupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CallId        string                 `protobuf:"bytes,1,opt,name=call_id,json=callId,proto3" json:"call_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HangupRequest) Reset() {
	*x = HangupRequest{}
	mi := &file_proto_webcall_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HangupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HangupRequest) ProtoMessage() {}

func (x *HangupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_webcall_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HangupRequest.ProtoReflect.Descriptor instead.
func (*HangupRequest) Descriptor() ([]byte, []int) {
	return file_proto_webcall_proto_rawDescGZIP(), []int{8}
}

func (x *HangupRequest) GetCallId() string {
	if x != nil {
		return x.CallId
	}
	return ""
}

// DtmfRequest sends one digit toward the callee (RFC 4733 out-of-band,
// SIP INFO fallback).
type DtmfRequest struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	CallId string                 `protobuf:"bytes,1,opt,name=call_id,json=callId,proto3" json:"call_id,omitempty"`
	// One of 0-9, *, #, A-D.
	Digit string `protobuf:"bytes,2,opt,name=digit,proto3" json:"digit,omitempty"`
	// Key press duration in ms (0 = 100).
	DurationMs    uint32 `protobuf:"varint,3,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DtmfRequest) Reset() {
	*x = DtmfRequest{}
	mi := &file_proto_webcall_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DtmfRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DtmfRequest) ProtoMessage() {}

func (x *DtmfRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_webcall_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DtmfRequest.ProtoReflect.Descriptor instead.
func (*DtmfRequest) Descriptor() ([]byte, []int) {
	return file_proto_webcall_proto_rawDescGZIP(), []int{9}
}

func (x *DtmfRequest) GetCallId() string {
	if x != nil {
		return x.CallId
	}
	return ""
}

func (x *DtmfRequest) GetDigit() string {
	if x != nil {
		return x.Digit
	}
	return ""
}

func (x *DtmfRequest) GetDurationMs() uint32 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

// DtmfEvent reports a digit received from the callee.
type DtmfEvent struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	CallId string                 `protobuf:"bytes,1,opt,name=call_id,json=callId,proto3" json:"call_id,omitempty"`
	Digit  string                 `protobuf:"bytes,2,opt,name=digit,proto3" json:"digit,omitempty"`
	// Detection method: rfc4733 or inband.
	Method        string `protobuf:"bytes,3,opt,name=method,proto3" json:"method,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DtmfEvent) Reset() {
	*x = DtmfEvent{}
	mi := &file_proto_webcall_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DtmfEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DtmfEvent) ProtoMessage() {}

func (x *DtmfEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_webcall_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DtmfEvent.ProtoReflect.Descriptor instead.
func (*DtmfEvent) Descriptor() ([]byte, []int) {
	return file_proto_webcall_proto_rawDescGZIP(), []int{10}
}

func (x *DtmfEvent) GetCallId() string {
	if x != nil {
		return x.CallId
	}
	return ""
}

func (x *DtmfEvent) GetDigit() string {
	if x != nil {
		return x.Digit
	}
	return ""
}

func (x *DtmfEvent) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

// MediaStart announces the audio format for one call, right before its first
// AudioFrame flows. Sent by the server after the call is answered.
type MediaStart struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	CallId string                 `protobuf:"bytes,1,opt,name=call_id,json=callId,proto3" json:"call_id,omitempty"`
	// Audio codec of the frames: "L16" (PCM16) in v1.
	Codec         string `protobuf:"bytes,2,opt,name=codec,proto3" json:"codec,omitempty"`
	SampleRate    uint32 `protobuf:"varint,3,opt,name=sample_rate,json=sampleRate,proto3" json:"sample_rate,omitempty"` // 8000
	FrameMs       uint32 `protobuf:"varint,4,opt,name=frame_ms,json=frameMs,proto3" json:"frame_ms,omitempty"`          // 20
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MediaStart) Reset() {
	*x = MediaStart{}
	mi := &file_proto_webcall_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MediaStart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MediaStart) ProtoMessage() {}

func (x *MediaStart) ProtoReflect() protoreflect.Message {
	mi := &file_proto_webcall_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MediaStart.ProtoReflect.Descriptor instead.
func (*MediaStart) Descriptor() ([]byte, []int) {
	return file_proto_webcall_proto_rawDescGZIP(), []int{11}
}

func (x *MediaStart) GetCallId() string {
	if x != nil {
		return x.CallId
	}
	return ""
}

func (x *MediaStart) GetCodec() string {
	if x != nil {
		return x.Codec
	}
	return ""
}

func (x *MediaStart) GetSampleRate() uint32 {
	if x != nil {
		return x.SampleRate
	}
	return 0
}

func (x *MediaStart) GetFrameMs() uint32 {
	if x != nil {
		return x.FrameMs
	}
	return 0
}

// AudioFrame carries one packet of phone audio, both directions. Timestamps
// advance by 160 per frame at 20 ms / 8 kHz.
type AudioFrame struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	CallId string                 `protobuf:"bytes,1,opt,name=call_id,json=callId,proto3" json:"call_id,omitempty"`
	// Per-call monotonic frame counter.
	Seq uint32 `protobuf:"varint,2,opt,name=seq,proto3" json:"seq,omitempty"`
	// RTP-style sample timestamp (wraps at 2^32).
	Timestamp uint32 `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// PCM16 little-endian samples, 8000 Hz mono.
	Pcm           []byte `protobuf:"bytes,4,opt,name=pcm,proto3" json:"pcm,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AudioFrame) Reset() {
	*x = AudioFrame{}
	mi := &file_proto_webcall_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AudioFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AudioFrame) ProtoMessage() {}

func (x *AudioFrame) ProtoReflect() protoreflect.Message {
	mi := &file_proto_webcall_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AudioFrame.ProtoReflect.Descriptor instead.
func (*AudioFrame) Descriptor() ([]byte, []int) {
	return file_proto_webcall_proto_rawDescGZIP(), []int{12}
}

func (x *AudioFrame) GetCallId() string {
	if x != nil {
		return x.CallId
	}
	return ""
}

func (x *AudioFrame) GetSeq() uint32 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *AudioFrame) GetTimestamp() uint32 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *AudioFrame) GetPcm() []byte {
	if x != nil {
		return x.Pcm
	}
	return nil
}

type Ping struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nonce         uint64                 `protobuf:"varint,1,opt,name=nonce,proto3" json:"nonce,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ping) Reset() {
	*x = Ping{}
	mi := &file_proto_webcall_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ping) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ping) ProtoMessage() {}

func (x *Ping) ProtoReflect() protoreflect.Message {
	mi := &file_proto_webcall_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ping.ProtoReflect.Descriptor instead.
func (*Ping) Descriptor() ([]byte, []int) {
	return file_proto_webcall_proto_rawDescGZIP(), []int{13}
}

func (x *Ping) GetNonce() uint64 {
	if x != nil {
		return x.Nonce
	}
	return 0
}

type Pong struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nonce         uint64                 `protobuf:"varint,1,opt,name=nonce,proto3" json:"nonce,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pong) Reset() {
	*x = Pong{}
	mi := &file_proto_webcall_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pong) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pong) ProtoMessage() {}

func (x *Pong) ProtoReflect() protoreflect.Message {
	mi := &file_proto_webcall_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pong.ProtoReflect.Descriptor instead.
func (*Pong) Descriptor() ([]byte, []int) {
	return file_proto_webcall_proto_rawDescGZIP(), []int{14}
}

func (x *Pong) GetNonce() uint64 {
	if x != nil {
		return x.Nonce
	}
	return 0
}

// TransferRequest connects the far party of an answered call to an
// outside number dialed through the same line, then releases the client:
// the two remote parties keep talking, the operator is free. The server
// presents the ORIGINAL caller's number to the outside party when the
// provider allows it (falling back to the line's own number).
type TransferRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The answered call to transfer away.
	CallId string `protobuf:"bytes,1,opt,name=call_id,json=callId,proto3" json:"call_id,omitempty"`
	// Destination: a plain number ("+98922222222") or full SIP URI.
	To            string `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransferRequest) Reset() {
	*x = TransferRequest{}
	mi := &file_proto_webcall_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferRequest) ProtoMessage() {}

func (x *TransferRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_webcall_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferRequest.ProtoReflect.Descriptor instead.
func (*TransferRequest) Descriptor() ([]byte, []int) {
	return file_proto_webcall_proto_rawDescGZIP(), []int{15}
}

func (x *TransferRequest) GetCallId() string {
	if x != nil {
		return x.CallId
	}
	return ""
}

func (x *TransferRequest) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

// TransferEvent reports transfer progress.
type TransferEvent struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	CallId string                 `protobuf:"bytes,1,opt,name=call_id,json=callId,proto3" json:"call_id,omitempty"`
	// dialing | answered | failed
	State string `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`
	// Human detail: the dialed number, or the failure reason. On "failed"
	// the original call survives untouched.
	Detail        string `protobuf:"bytes,3,opt,name=detail,proto3" json:"detail,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransferEvent) Reset() {
	*x = TransferEvent{}
	mi := &file_proto_webcall_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferEvent) ProtoMessage() {}

func (x *TransferEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_webcall_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferEvent.ProtoReflect.Descriptor instead.
func (*TransferEvent) Descriptor() ([]byte, []int) {
	return file_proto_webcall_proto_rawDescGZIP(), []int{16}
}

func (x *TransferEvent) GetCallId() string {
	if x != nil {
		return x.CallId
	}
	return ""
}

func (x *TransferEvent) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *TransferEvent) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

// ConferenceInvite dials another person and merges them with the existing
// call into one mixed group call: everyone hears everyone. The new leg is
// a normal call (its own call_id, lifecycle events and CDR); hanging it
// up removes just that participant. When the client hangs up the anchor
// call it leaves the room — the remaining parties keep talking.
type ConferenceInvite struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The answered call that becomes the group call.
	CallId string `protobuf:"bytes,1,opt,name=call_id,json=callId,proto3" json:"call_id,omitempty"`
	// Who to dial into the room.
	To string `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`
	// Optional display name for the new participant.
	DisplayName   string `protobuf:"bytes,3,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConferenceInvite) Reset() {
	*x = ConferenceInvite{}
	mi := &file_proto_webcall_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConferenceInvite) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConferenceInvite) ProtoMessage() {}

func (x *ConferenceInvite) ProtoReflect() protoreflect.Message {
	mi := &file_proto_webcall_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConferenceInvite.ProtoReflect.Descriptor instead.
func (*ConferenceInvite) Descriptor() ([]byte, []int) {
	return file_proto_webcall_proto_rawDescGZIP(), []int{17}
}

func (x *ConferenceInvite) GetCallId() string {
	if x != nil {
		return x.CallId
	}
	return ""
}

func (x *ConferenceInvite) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *ConferenceInvite) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

// ConferenceEvent reports group-call membership changes.
type ConferenceEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The anchor call id (the room).
	CallId string `protobuf:"bytes,1,opt,name=call_id,json=callId,proto3" json:"call_id,omitempty"`
	// Remote identity of the participant that joined or left.
	Participant string `protobuf:"bytes,2,opt,name=participant,proto3" json:"participant,omitempty"`
	// joined | left
	Action string `protobuf:"bytes,3,opt,name=action,proto3" json:"action,omitempty"`
	// Headcount after the change (including the client).
	Participants  uint32 `protobuf:"varint,4,opt,name=participants,proto3" json:"participants,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConferenceEvent) Reset() {
	*x = ConferenceEvent{}
	mi := &file_proto_webcall_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConferenceEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConferenceEvent) ProtoMessage() {}

func (x *ConferenceEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_webcall_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConferenceEvent.ProtoReflect.Descriptor instead.
func (*ConferenceEvent) Descriptor() ([]byte, []int) {
	return file_proto_webcall_proto_rawDescGZIP(), []int{18}
}

func (x *ConferenceEvent) GetCallId() string {
	if x != nil {
		return x.CallId
	}
	return ""
}

func (x *ConferenceEvent) GetParticipant() string {
	if x != nil {
		return x.Participant
	}
	return ""
}

func (x *ConferenceEvent) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *ConferenceEvent) GetParticipants() uint32 {
	if x != nil {
		return x.Participants
	}
	return 0
}

type Bye struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Reason string                 `protobuf:"bytes,1,opt,name=reason,proto3" json:"reason,omitempty"`
	// 1 auth_failed, 2 line_unknown, 3 line_no_password, 4 version_mismatch,
	// 5 protocol_error, 6 server_shutdown, 7 idle_timeout
	Code          uint32 `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Bye) Reset() {
	*x = Bye{}
	mi := &file_proto_webcall_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Bye) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bye) ProtoMessage() {}

func (x *Bye) ProtoReflect() protoreflect.Message {
	mi := &file_proto_webcall_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bye.ProtoReflect.Descriptor instead.
func (*Bye) Descriptor() ([]byte, []int) {
	return file_proto_webcall_proto_rawDescGZIP(), []int{19}
}

func (x *Bye) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *Bye) GetCode() uint32 {
	if x != nil {
		return x.Code
	}
	return 0
}

// InboundSubscription toggles incoming-call delivery for this session.
type InboundSubscription struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// true = deliver incoming calls to this client; false = stop.
	Want          bool `protobuf:"varint,1,opt,name=want,proto3" json:"want,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InboundSubscription) Reset() {
	*x = InboundSubscription{}
	mi := &file_proto_webcall_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InboundSubscription) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InboundSubscription) ProtoMessage() {}

func (x *InboundSubscription) ProtoReflect() protoreflect.Message {
	mi := &file_proto_webcall_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InboundSubscription.ProtoReflect.Descriptor instead.
func (*InboundSubscription) Descriptor() ([]byte, []int) {
	return file_proto_webcall_proto_rawDescGZIP(), []int{20}
}

func (x *InboundSubscription) GetWant() bool {
	if x != nil {
		return x.Want
	}
	return false
}

// InboundAck confirms a subscription change took effect.
type InboundAck struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The now-current subscription state.
	Want bool `protobuf:"varint,1,opt,name=want,proto3" json:"want,omitempty"`
	// Non-empty when the subscription could not be changed.
	Error         string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InboundAck) Reset() {
	*x = InboundAck{}
	mi := &file_proto_webcall_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InboundAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InboundAck) ProtoMessage() {}

func (x *InboundAck) ProtoReflect() protoreflect.Message {
	mi := &file_proto_webcall_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InboundAck.ProtoReflect.Descriptor instead.
func (*InboundAck) Descriptor() ([]byte, []int) {
	return file_proto_webcall_proto_rawDescGZIP(), []int{21}
}

func (x *InboundAck) GetWant() bool {
	if x != nil {
		return x.Want
	}
	return false
}

func (x *InboundAck) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// IncomingCallEvent announces a call that arrived at the line. The client
// answers with AcceptRequest or RejectRequest before the ring window
// closes; after that the call is released as missed. While the offer is
// pending the caller hears ringback.
type IncomingCallEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The id the client uses to accept, reject or (once accepted) hang up.
	CallId string `protobuf:"bytes,1,opt,name=call_id,json=callId,proto3" json:"call_id,omitempty"`
	// Caller identity: SIP From user part ("15005554117").
	From string `protobuf:"bytes,2,opt,name=from,proto3" json:"from,omitempty"`
	// Caller display name when the provider sent one.
	FromDisplay string `protobuf:"bytes,3,opt,name=from_display,json=fromDisplay,proto3" json:"from_display,omitempty"`
	// Dialed destination (the line's number or extension).
	To string `protobuf:"bytes,4,opt,name=to,proto3" json:"to,omitempty"`
	// Seconds the client has to accept (informational; server-enforced).
	RingSec       uint32 `protobuf:"varint,5,opt,name=ring_sec,json=ringSec,proto3" json:"ring_sec,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IncomingCallEvent) Reset() {
	*x = IncomingCallEvent{}
	mi := &file_proto_webcall_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IncomingCallEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IncomingCallEvent) ProtoMessage() {}

func (x *IncomingCallEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_webcall_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IncomingCallEvent.ProtoReflect.Descriptor instead.
func (*IncomingCallEvent) Descriptor() ([]byte, []int) {
	return file_proto_webcall_proto_rawDescGZIP(), []int{22}
}

func (x *IncomingCallEvent) GetCallId() string {
	if x != nil {
		return x.CallId
	}
	return ""
}

func (x *IncomingCallEvent) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *IncomingCallEvent) GetFromDisplay() string {
	if x != nil {
		return x.FromDisplay
	}
	return ""
}

func (x *IncomingCallEvent) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *IncomingCallEvent) GetRingSec() uint32 {
	if x != nil {
		return x.RingSec
	}
	return 0
}

// AcceptRequest picks up an announced incoming call. From then on the call
// behaves exactly like an answered outbound call: CallEvent "answered",
// MediaStart, bidirectional AudioFrames, DTMF, transfer and conference.
type AcceptRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CallId        string                 `protobuf:"bytes,1,opt,name=call_id,json=callId,proto3" json:"call_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcceptRequest) Reset() {
	*x = AcceptRequest{}
	mi := &file_proto_webcall_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcceptRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcceptRequest) ProtoMessage() {}

func (x *AcceptRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_webcall_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcceptRequest.ProtoReflect.Descriptor instead.
func (*AcceptRequest) Descriptor() ([]byte, []int) {
	return file_proto_webcall_proto_rawDescGZIP(), []int{23}
}

func (x *AcceptRequest) GetCallId() string {
	if x != nil {
		return x.CallId
	}
	return ""
}

// RejectRequest declines an announced incoming call (the caller is hung
// up on; the client keeps its other calls).
type RejectRequest struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	CallId string                 `protobuf:"bytes,1,opt,name=call_id,json=callId,proto3" json:"call_id,omitempty"`
	// Optional reason, logged and shown in the call detail ("busy", ...).
	Reason        string `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RejectRequest) Reset() {
	*x = RejectRequest{}
	mi := &file_proto_webcall_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RejectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RejectRequest) ProtoMessage() {}

func (x *RejectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_webcall_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RejectRequest.ProtoReflect.Descriptor instead.
func (*RejectRequest) Descriptor() ([]byte, []int) {
	return file_proto_webcall_proto_rawDescGZIP(), []int{24}
}

func (x *RejectRequest) GetCallId() string {
	if x != nil {
		return x.CallId
	}
	return ""
}

func (x *RejectRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

var File_proto_webcall_proto protoreflect.FileDescriptor

var file_proto_webcall_proto_rawDesc = string([]byte{
	0x0a, 0x13, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x77, 0x65, 0x62, 0x63, 0x61, 0x6c, 0x6c, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x14, 0x76, 0x6f, 0x69, 0x63, 0x65, 0x6c, 0x69, 0x6e, 0x65,
	0x2e, 0x77, 0x65, 0x62, 0x63, 0x61, 0x6c, 0x6c, 0x2e, 0x76, 0x31, 0x22, 0x64, 0x0a, 0x0c, 0x48,
	0x65, 0x6c, 0x6c, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x76,
	0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x76, 0x65,
	0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x17, 0x0a, 0x07, 0x6c, 0x69, 0x6e, 0x65, 0x5f, 0x69, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6c, 0x69, 0x6e, 0x65, 0x49, 0x64, 0x12, 0x21,
	0x0a, 0x0c, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x6e, 0x6f, 0x6e, 0x63, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x0b, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x4e, 0x6f, 0x6e, 0x63,
	0x65, 0x22, 0x62, 0x0a, 0x0d, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x21, 0x0a, 0x0c,
	0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x5f, 0x6e, 0x6f, 0x6e, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x0b, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x4e, 0x6f, 0x6e, 0x63, 0x65, 0x12,
	0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x65, 0x72, 0x72, 0x6f, 0x72, 0x22, 0xe1, 0x0a, 0x0a, 0x08, 0x45, 0x6e, 0x76, 0x65, 0x6c, 0x6f,
	0x70, 0x65, 0x12, 0x46, 0x0a, 0x0c, 0x61, 0x75, 0x74, 0x68, 0x5f, 0x63, 0x6f, 0x6e, 0x66, 0x69,
	0x72, 0x6d, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x76, 0x6f, 0x69, 0x63, 0x65,
	0x6c, 0x69, 0x6e, 0x65, 0x2e, 0x77, 0x65, 0x62, 0x63, 0x61, 0x6c, 0x6c, 0x2e, 0x76, 0x31, 0x2e,
	0x41, 0x75, 0x74, 0x68, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x72, 0x6d, 0x48, 0x00, 0x52, 0x0b, 0x61,
	0x75, 0x74, 0x68, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x72, 0x6d, 0x12, 0x43, 0x0a, 0x0b, 0x61, 0x75,
	0x74, 0x68, 0x5f, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x20, 0x2e, 0x76, 0x6f, 0x69, 0x63, 0x65, 0x6c, 0x69, 0x6e, 0x65, 0x2e, 0x77, 0x65, 0x62, 0x63,
	0x61, 0x6c, 0x6c, 0x2e, 0x76, 0x31, 0x2e, 0x41, 0x75, 0x74, 0x68, 0x52, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x48, 0x00, 0x52, 0x0a, 0x61, 0x75, 0x74, 0x68, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12,
	0x37, 0x0a, 0x04, 0x64, 0x69, 0x61, 0x6c, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x21, 0x2e,
	0x76, 0x6f, 0x69, 0x63, 0x65, 0x6c, 0x69, 0x6e, 0x65, 0x2e, 0x77, 0x65, 0x62, 0x63, 0x61, 0x6c,
	0x6c, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x69, 0x61, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x48, 0x00, 0x52, 0x04, 0x64, 0x69, 0x61, 0x6c, 0x12, 0x40, 0x0a, 0x0a, 0x63, 0x61, 0x6c, 0x6c,
	0x5f, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x76,
	0x6f, 0x69, 0x63, 0x65, 0x6c, 0x69, 0x6e, 0x65, 0x2e, 0x77, 0x65, 0x62, 0x63, 0x61, 0x6c, 0x6c,
	0x2e, 0x76, 0x31, 0x2e, 0x43, 0x61, 0x6c, 0x6c, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x48, 0x00, 0x52,
	0x09, 0x63, 0x61, 0x6c, 0x6c, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x3d, 0x0a, 0x06, 0x68, 0x61,
	0x6e, 0x67, 0x75, 0x70, 0x18, 0x0e, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x23, 0x2e, 0x76, 0x6f, 0x69,
	0x63, 0x65, 0x6c, 0x69, 0x6e, 0x65, 0x2e, 0x77, 0x65, 0x62, 0x63, 0x61, 0x6c, 0x6c, 0x2e, 0x76,
	0x31, 0x2e, 0x48, 0x61, 0x6e, 0x67, 0x75, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x48,
	0x00, 0x52, 0x06, 0x68, 0x61, 0x6e, 0x67, 0x75, 0x70, 0x12, 0x37, 0x0a, 0x04, 0x64, 0x74, 0x6d,
	0x66, 0x18, 0x0f, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x76, 0x6f, 0x69, 0x63, 0x65, 0x6c,
	0x69, 0x6e, 0x65, 0x2e, 0x77, 0x65, 0x62, 0x63, 0x61, 0x6c, 0x6c, 0x2e, 0x76, 0x31, 0x2e, 0x44,
	0x74, 0x6d, 0x66, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x48, 0x00, 0x52, 0x04, 0x64, 0x74,
	0x6d, 0x66, 0x12, 0x40, 0x0a, 0x0a, 0x64, 0x74, 0x6d, 0x66, 0x5f, 0x65, 0x76, 0x65, 0x6e, 0x74,
	0x18, 0x10, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x76, 0x6f, 0x69, 0x63, 0x65, 0x6c, 0x69,
	0x6e, 0x65, 0x2e, 0x77, 0x65, 0x62, 0x63, 0x61, 0x6c, 0x6c, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x74,
	0x6d, 0x66, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x48, 0x00, 0x52, 0x09, 0x64, 0x74, 0x6d, 0x66, 0x45,
	0x76, 0x65, 0x6e, 0x74, 0x12, 0x43, 0x0a, 0x0b, 0x6d, 0x65, 0x64, 0x69, 0x61, 0x5f, 0x73, 0x74,
	0x61, 0x72, 0x74, 0x18, 0x11, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x76, 0x6f, 0x69, 0x63,
	0x65, 0x6c, 0x69, 0x6e, 0x65, 0x2e, 0x77, 0x65, 0x62, 0x63, 0x61, 0x6c, 0x6c, 0x2e, 0x76, 0x31,
	0x2e, 0x4d, 0x65, 0x64, 0x69, 0x61, 0x53, 0x74, 0x61, 0x72, 0x74, 0x48, 0x00, 0x52, 0x0a, 0x6d,
	0x65, 0x64, 0x69, 0x61, 0x53, 0x74, 0x61, 0x72, 0x74, 0x12, 0x38, 0x0a, 0x05, 0x61, 0x75, 0x64,
	0x69, 0x6f, 0x18, 0x12, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x76, 0x6f, 0x69, 0x63, 0x65,
	0x6c, 0x69, 0x6e, 0x65, 0x2e, 0x77, 0x65, 0x62, 0x63, 0x61, 0x6c, 0x6c, 0x2e, 0x76, 0x31, 0x2e,
	0x41, 0x75, 0x64, 0x69, 0x6f, 0x46, 0x72, 0x61, 0x6d, 0x65, 0x48, 0x00, 0x52, 0x05, 0x61, 0x75,
	0x64, 0x69, 0x6f, 0x12, 0x30, 0x0a, 0x04, 0x70, 0x69, 0x6e, 0x67, 0x18, 0x13, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1a, 0x2e, 0x76, 0x6f, 0x69, 0x63, 0x65, 0x6c, 0x69, 0x6e, 0x65, 0x2e, 0x77, 0x65,
	0x62, 0x63, 0x61, 0x6c, 0x6c, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x69, 0x6e, 0x67, 0x48, 0x00, 0x52,
	0x04, 0x70, 0x69, 0x6e, 0x67, 0x12, 0x30, 0x0a, 0x04, 0x70, 0x6f, 0x6e, 0x67, 0x18, 0x14, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x76, 0x6f, 0x69, 0x63, 0x65, 0x6c, 0x69, 0x6e, 0x65, 0x2e,
	0x77, 0x65, 0x62, 0x63, 0x61, 0x6c, 0x6c, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x6f, 0x6e, 0x67, 0x48,
	0x00, 0x52, 0x04, 0x70, 0x6f, 0x6e, 0x67, 0x12, 0x2d, 0x0a, 0x03, 0x62, 0x79, 0x65, 0x18, 0x15,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x76, 0x6f, 0x69, 0x63, 0x65, 0x6c, 0x69, 0x6e, 0x65,
	0x2e, 0x77, 0x65, 0x62, 0x63, 0x61, 0x6c, 0x6c, 0x2e, 0x76, 0x31, 0x2e, 0x42, 0x79, 0x65, 0x48,
	0x00, 0x52, 0x03, 0x62, 0x79, 0x65, 0x12, 0x43, 0x0a, 0x08, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x66,
	0x65, 0x72, 0x18, 0x1e, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x25, 0x2e, 0x76, 0x6f, 0x69, 0x63, 0x65,
	0x6c, 0x69, 0x6e, 0x65, 0x2e, 0x77, 0x65, 0x62, 0x63, 0x61, 0x6c, 0x6c, 0x2e, 0x76, 0x31, 0x2e,
	0x54, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x48,
	0x00, 0x52, 0x08, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x12, 0x46, 0x0a, 0x0b, 0x74,
	0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x5f, 0x65, 0x76, 0x18, 0x1f, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x23, 0x2e, 0x76, 0x6f, 0x69, 0x63, 0x65, 0x6c, 0x69, 0x6e, 0x65, 0x2e, 0x77, 0x65, 0x62,
	0x63, 0x61, 0x6c, 0x6c, 0x2e, 0x76, 0x31, 0x2e, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72,
	0x45, 0x76, 0x65, 0x6e, 0x74, 0x48, 0x00, 0x52, 0x0a, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65,
	0x72, 0x45, 0x76, 0x12, 0x49, 0x0a, 0x0b, 0x63, 0x6f, 0x6e, 0x66, 0x5f, 0x69, 0x6e, 0x76, 0x69,
	0x74, 0x65, 0x18, 0x20, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x26, 0x2e, 0x76, 0x6f, 0x69, 0x63, 0x65,
	0x6c, 0x69, 0x6e, 0x65, 0x2e, 0x77, 0x65, 0x62, 0x63, 0x61, 0x6c, 0x6c, 0x2e, 0x76, 0x31, 0x2e,
	0x43, 0x6f, 0x6e, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x49, 0x6e, 0x76, 0x69, 0x74, 0x65,
	0x48, 0x00, 0x52, 0x0a, 0x63, 0x6f, 0x6e, 0x66, 0x49, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x12, 0x46,
	0x0a, 0x0a, 0x63, 0x6f, 0x6e, 0x66, 0x5f, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x18, 0x21, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x25, 0x2e, 0x76, 0x6f, 0x69, 0x63, 0x65, 0x6c, 0x69, 0x6e, 0x65, 0x2e, 0x77,
	0x65, 0x62, 0x63, 0x61, 0x6c, 0x6c, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x6f, 0x6e, 0x66, 0x65, 0x72,
	0x65, 0x6e, 0x63, 0x65, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x48, 0x00, 0x52, 0x09, 0x63, 0x6f, 0x6e,
	0x66, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x4c, 0x0a, 0x0b, 0x69, 0x6e, 0x62, 0x6f, 0x75, 0x6e,
	0x64, 0x5f, 0x73, 0x75, 0x62, 0x18, 0x22, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x29, 0x2e, 0x76, 0x6f,
	0x69, 0x63, 0x65, 0x6c, 0x69, 0x6e, 0x65, 0x2e, 0x77, 0x65, 0x62, 0x63, 0x61, 0x6c, 0x6c, 0x2e,
	0x76, 0x31, 0x2e, 0x49, 0x6e, 0x62, 0x6f, 0x75, 0x6e, 0x64, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72,
	0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x48, 0x00, 0x52, 0x0a, 0x69, 0x6e, 0x62, 0x6f, 0x75, 0x6e,
	0x64, 0x53, 0x75, 0x62, 0x12, 0x43, 0x0a, 0x0b, 0x69, 0x6e, 0x62, 0x6f, 0x75, 0x6e, 0x64, 0x5f,
	0x61, 0x63, 0x6b, 0x18, 0x23, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x76, 0x6f, 0x69, 0x63,
	0x65, 0x6c, 0x69, 0x6e, 0x65, 0x2e, 0x77, 0x65, 0x62, 0x63, 0x61, 0x6c, 0x6c, 0x2e, 0x76, 0x31,
	0x2e, 0x49, 0x6e, 0x62, 0x6f, 0x75, 0x6e, 0x64, 0x41, 0x63, 0x6b, 0x48, 0x00, 0x52, 0x0a, 0x69,
	0x6e, 0x62, 0x6f, 0x75, 0x6e, 0x64, 0x41, 0x63, 0x6b, 0x12, 0x45, 0x0a, 0x08, 0x69, 0x6e, 0x63,
	0x6f, 0x6d, 0x69, 0x6e, 0x67, 0x18, 0x24, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x27, 0x2e, 0x76, 0x6f,
	0x69, 0x63, 0x65, 0x6c, 0x69, 0x6e, 0x65, 0x2e, 0x77, 0x65, 0x62, 0x63, 0x61, 0x6c, 0x6c, 0x2e,
	0x76, 0x31, 0x2e, 0x49, 0x6e, 0x63, 0x6f, 0x6d, 0x69, 0x6e, 0x67, 0x43, 0x61, 0x6c, 0x6c, 0x45,
	0x76, 0x65, 0x6e, 0x74, 0x48, 0x00, 0x52, 0x08, 0x69, 0x6e, 0x63, 0x6f, 0x6d, 0x69, 0x6e, 0x67,
	0x12, 0x3d, 0x0a, 0x06, 0x61, 0x63, 0x63, 0x65, 0x70, 0x74, 0x18, 0x25, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x23, 0x2e, 0x76, 0x6f, 0x69, 0x63, 0x65, 0x6c, 0x69, 0x6e, 0x65, 0x2e, 0x77, 0x65, 0x62,
	0x63, 0x61, 0x6c, 0x6c, 0x2e, 0x76, 0x31, 0x2e, 0x41, 0x63, 0x63, 0x65, 0x70, 0x74, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x48, 0x00, 0x52, 0x06, 0x61, 0x63, 0x63, 0x65, 0x70, 0x74, 0x12,
	0x3d, 0x0a, 0x06, 0x72, 0x65, 0x6a, 0x65, 0x63, 0x74, 0x18, 0x26, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x23, 0x2e, 0x76, 0x6f, 0x69, 0x63, 0x65, 0x6c, 0x69, 0x6e, 0x65, 0x2e, 0x77, 0x65, 0x62, 0x63,
	0x61, 0x6c, 0x6c, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x65, 0x6a, 0x65, 0x63, 0x74, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x48, 0x00, 0x52, 0x06, 0x72, 0x65, 0x6a, 0x65, 0x63, 0x74, 0x42, 0x09,
	0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x22, 0x65, 0x0a, 0x0b, 0x41, 0x75, 0x74,
	0x68, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x72, 0x6d, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x72, 0x6f, 0x6f,
	0x66, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x70, 0x72, 0x6f, 0x6f, 0x66, 0x12, 0x21,
	0x0a, 0x0c, 0x64, 0x69, 0x73, 0x70, 0x6c, 0x61, 0x79, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x69, 0x73, 0x70, 0x6c, 0x61, 0x79, 0x4e, 0x61, 0x6d,
	0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x75, 0x73, 0x65, 0x72, 0x41, 0x67, 0x65, 0x6e, 0x74,
	0x22, 0x66, 0x0a, 0x0a, 0x41, 0x75, 0x74, 0x68, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x0e,
	0x0a, 0x02, 0x6f, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x02, 0x6f, 0x6b, 0x12, 0x14,
	0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65,
	0x72, 0x72, 0x6f, 0x72, 0x12, 0x32, 0x0a, 0x04, 0x6c, 0x69, 0x6e, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x76, 0x6f, 0x69, 0x63, 0x65, 0x6c, 0x69, 0x6e, 0x65, 0x2e, 0x77,
	0x65, 0x62, 0x63, 0x61, 0x6c, 0x6c, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69, 0x6e, 0x65, 0x49, 0x6e,
	0x66, 0x6f, 0x52, 0x04, 0x6c, 0x69, 0x6e, 0x65, 0x22, 0xf0, 0x01, 0x0a, 0x08, 0x4c, 0x69, 0x6e,
	0x65, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x21, 0x0a,
	0x0c, 0x64, 0x69, 0x73, 0x70, 0x6c, 0x61, 0x79, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x69, 0x73, 0x70, 0x6c, 0x61, 0x79, 0x4e, 0x61, 0x6d, 0x65,
	0x12, 0x1b, 0x0a, 0x09, 0x72, 0x65, 0x67, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x72, 0x65, 0x67, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x1e, 0x0a,
	0x0a, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x65, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x0a, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x65, 0x64, 0x12, 0x12, 0x0a,
	0x04, 0x68, 0x6f, 0x6f, 0x6b, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x68, 0x6f, 0x6f,
	0x6b, 0x12, 0x21, 0x0a, 0x0c, 0x61, 0x63, 0x74, 0x69, 0x76, 0x65, 0x5f, 0x63, 0x61, 0x6c, 0x6c,
	0x73, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0b, 0x61, 0x63, 0x74, 0x69, 0x76, 0x65, 0x43,
	0x61, 0x6c, 0x6c, 0x73, 0x12, 0x25, 0x0a, 0x0e, 0x6d, 0x61, 0x78, 0x5f, 0x63, 0x6f, 0x6e, 0x63,
	0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0d, 0x6d, 0x61,
	0x78, 0x43, 0x6f, 0x6e, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x22, 0x61, 0x0a, 0x0b, 0x44,
	0x69, 0x61, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x74, 0x6f,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x74, 0x6f, 0x12, 0x21, 0x0a, 0x0c, 0x64, 0x69,
	0x73, 0x70, 0x6c, 0x61, 0x79, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0b, 0x64, 0x69, 0x73, 0x70, 0x6c, 0x61, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1f, 0x0a,
	0x0b, 0x74, 0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74, 0x5f, 0x73, 0x65, 0x63, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x0a, 0x74, 0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74, 0x53, 0x65, 0x63, 0x22, 0x99,
	0x01, 0x0a, 0x09, 0x43, 0x61, 0x6c, 0x6c, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x17, 0x0a, 0x07,
	0x63, 0x61, 0x6c, 0x6c, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x63,
	0x61, 0x6c, 0x6c, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x64,
	0x65, 0x74, 0x61, 0x69, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x64, 0x65, 0x74,
	0x61, 0x69, 0x6c, 0x12, 0x24, 0x0a, 0x0e, 0x61, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x65, 0x64, 0x5f,
	0x61, 0x74, 0x5f, 0x6d, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0c, 0x61, 0x6e, 0x73,
	0x77, 0x65, 0x72, 0x65, 0x64, 0x41, 0x74, 0x4d, 0x73, 0x12, 0x1f, 0x0a, 0x0b, 0x64, 0x75, 0x72,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x6d, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0a,
	0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4d, 0x73, 0x22, 0x28, 0x0a, 0x0d, 0x48, 0x61,
	0x6e, 0x67, 0x75, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x63,
	0x61, 0x6c, 0x6c, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x63, 0x61,
	0x6c, 0x6c, 0x49, 0x64, 0x22, 0x5d, 0x0a, 0x0b, 0x44, 0x74, 0x6d, 0x66, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x63, 0x61, 0x6c, 0x6c, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x63, 0x61, 0x6c, 0x6c, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05,
	0x64, 0x69, 0x67, 0x69, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x64, 0x69, 0x67,
	0x69, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x6d,
	0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0a, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x4d, 0x73, 0x22, 0x52, 0x0a, 0x09, 0x44, 0x74, 0x6d, 0x66, 0x45, 0x76, 0x65, 0x6e, 0x74,
	0x12, 0x17, 0x0a, 0x07, 0x63, 0x61, 0x6c, 0x6c, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x63, 0x61, 0x6c, 0x6c, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x64, 0x69, 0x67,
	0x69, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x64, 0x69, 0x67, 0x69, 0x74, 0x12,
	0x16, 0x0a, 0x06, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x22, 0x77, 0x0a, 0x0a, 0x4d, 0x65, 0x64, 0x69, 0x61,
	0x53, 0x74, 0x61, 0x72, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x63, 0x61, 0x6c, 0x6c, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x63, 0x61, 0x6c, 0x6c, 0x49, 0x64, 0x12, 0x14,
	0x0a, 0x05, 0x63, 0x6f, 0x64, 0x65, 0x63, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x63,
	0x6f, 0x64, 0x65, 0x63, 0x12, 0x1f, 0x0a, 0x0b, 0x73, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x5f, 0x72,
	0x61, 0x74, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0a, 0x73, 0x61, 0x6d, 0x70, 0x6c,
	0x65, 0x52, 0x61, 0x74, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x66, 0x72, 0x61, 0x6d, 0x65, 0x5f, 0x6d,
	0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x66, 0x72, 0x61, 0x6d, 0x65, 0x4d, 0x73,
	0x22, 0x67, 0x0a, 0x0a, 0x41, 0x75, 0x64, 0x69, 0x6f, 0x46, 0x72, 0x61, 0x6d, 0x65, 0x12, 0x17,
	0x0a, 0x07, 0x63, 0x61, 0x6c, 0x6c, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x63, 0x61, 0x6c, 0x6c, 0x49, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x65, 0x71, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x03, 0x73, 0x65, 0x71, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x69, 0x6d,
	0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x74, 0x69,
	0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x10, 0x0a, 0x03, 0x70, 0x63, 0x6d, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x70, 0x63, 0x6d, 0x22, 0x1c, 0x0a, 0x04, 0x50, 0x69, 0x6e,
	0x67, 0x12, 0x14, 0x0a, 0x05, 0x6e, 0x6f, 0x6e, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x05, 0x6e, 0x6f, 0x6e, 0x63, 0x65, 0x22, 0x1c, 0x0a, 0x04, 0x50, 0x6f, 0x6e, 0x67, 0x12,
	0x14, 0x0a, 0x05, 0x6e, 0x6f, 0x6e, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x05,
	0x6e, 0x6f, 0x6e, 0x63, 0x65, 0x22, 0x3a, 0x0a, 0x0f, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65,
	0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x63, 0x61, 0x6c, 0x6c,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x63, 0x61, 0x6c, 0x6c, 0x49,
	0x64, 0x12, 0x0e, 0x0a, 0x02, 0x74, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x74,
	0x6f, 0x22, 0x56, 0x0a, 0x0d, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x45, 0x76, 0x65,
	0x6e, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x63, 0x61, 0x6c, 0x6c, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x63, 0x61, 0x6c, 0x6c, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x73,
	0x74, 0x61, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x73, 0x74, 0x61, 0x74,
	0x65, 0x12, 0x16, 0x0a, 0x06, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x22, 0x5e, 0x0a, 0x10, 0x43, 0x6f, 0x6e,
	0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x49, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x12, 0x17, 0x0a,
	0x07, 0x63, 0x61, 0x6c, 0x6c, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x63, 0x61, 0x6c, 0x6c, 0x49, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x74, 0x6f, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x02, 0x74, 0x6f, 0x12, 0x21, 0x0a, 0x0c, 0x64, 0x69, 0x73, 0x70, 0x6c, 0x61,
	0x79, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x69,
	0x73, 0x70, 0x6c, 0x61, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x88, 0x01, 0x0a, 0x0f, 0x43, 0x6f,
	0x6e, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x17, 0x0a,
	0x07, 0x63, 0x61, 0x6c, 0x6c, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x63, 0x61, 0x6c, 0x6c, 0x49, 0x64, 0x12, 0x20, 0x0a, 0x0b, 0x70, 0x61, 0x72, 0x74, 0x69, 0x63,
	0x69, 0x70, 0x61, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x70, 0x61, 0x72,
	0x74, 0x69, 0x63, 0x69, 0x70, 0x61, 0x6e, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x12, 0x22, 0x0a, 0x0c, 0x70, 0x61, 0x72, 0x74, 0x69, 0x63, 0x69, 0x70, 0x61, 0x6e, 0x74, 0x73,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0c, 0x70, 0x61, 0x72, 0x74, 0x69, 0x63, 0x69, 0x70,
	0x61, 0x6e, 0x74, 0x73, 0x22, 0x31, 0x0a, 0x03, 0x42, 0x79, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x72,
	0x65, 0x61, 0x73, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x61,
	0x73, 0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x22, 0x29, 0x0a, 0x13, 0x49, 0x6e, 0x62, 0x6f, 0x75,
	0x6e, 0x64, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x12,
	0x0a, 0x04, 0x77, 0x61, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x04, 0x77, 0x61,
	0x6e, 0x74, 0x22, 0x36, 0x0a, 0x0a, 0x49, 0x6e, 0x62, 0x6f, 0x75, 0x6e, 0x64, 0x41, 0x63, 0x6b,
	0x12, 0x12, 0x0a, 0x04, 0x77, 0x61, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x04,
	0x77, 0x61, 0x6e, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x8e, 0x01, 0x0a, 0x11, 0x49,
	0x6e, 0x63, 0x6f, 0x6d, 0x69, 0x6e, 0x67, 0x43, 0x61, 0x6c, 0x6c, 0x45, 0x76, 0x65, 0x6e, 0x74,
	0x12, 0x17, 0x0a, 0x07, 0x63, 0x61, 0x6c, 0x6c, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x63, 0x61, 0x6c, 0x6c, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x66, 0x72, 0x6f,
	0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x66, 0x72, 0x6f, 0x6d, 0x12, 0x21, 0x0a,
	0x0c, 0x66, 0x72, 0x6f, 0x6d, 0x5f, 0x64, 0x69, 0x73, 0x70, 0x6c, 0x61, 0x79, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0b, 0x66, 0x72, 0x6f, 0x6d, 0x44, 0x69, 0x73, 0x70, 0x6c, 0x61, 0x79,
	0x12, 0x0e, 0x0a, 0x02, 0x74, 0x6f, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x74, 0x6f,
	0x12, 0x19, 0x0a, 0x08, 0x72, 0x69, 0x6e, 0x67, 0x5f, 0x73, 0x65, 0x63, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x07, 0x72, 0x69, 0x6e, 0x67, 0x53, 0x65, 0x63, 0x22, 0x28, 0x0a, 0x0d, 0x41,
	0x63, 0x63, 0x65, 0x70, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07,
	0x63, 0x61, 0x6c, 0x6c, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x63,
	0x61, 0x6c, 0x6c, 0x49, 0x64, 0x22, 0x40, 0x0a, 0x0d, 0x52, 0x65, 0x6a, 0x65, 0x63, 0x74, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x63, 0x61, 0x6c, 0x6c, 0x5f, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x63, 0x61, 0x6c, 0x6c, 0x49, 0x64, 0x12,
	0x16, 0x0a, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x42, 0x42, 0x5a, 0x40, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6d, 0x65, 0x68, 0x6d, 0x61, 0x6e, 0x6e, 0x61, 0x76, 0x61,
	0x7a, 0x2f, 0x76, 0x6f, 0x69, 0x63, 0x65, 0x6c, 0x69, 0x6e, 0x65, 0x2d, 0x70, 0x68, 0x6f, 0x6e,
	0x65, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x76, 0x63, 0x70, 0x2f, 0x70,
	0x62, 0x3b, 0x77, 0x65, 0x62, 0x63, 0x61, 0x6c, 0x6c, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
})

var (
	file_proto_webcall_proto_rawDescOnce sync.Once
	file_proto_webcall_proto_rawDescData []byte
)

func file_proto_webcall_proto_rawDescGZIP() []byte {
	file_proto_webcall_proto_rawDescOnce.Do(func() {
		file_proto_webcall_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_webcall_proto_rawDesc), len(file_proto_webcall_proto_rawDesc)))
	})
	return file_proto_webcall_proto_rawDescData
}

var file_proto_webcall_proto_msgTypes = make([]protoimpl.MessageInfo, 25)
var file_proto_webcall_proto_goTypes = []any{
	(*HelloRequest)(nil),        // 0: voiceline.webcall.v1.HelloRequest
	(*HelloResponse)(nil),       // 1: voiceline.webcall.v1.HelloResponse
	(*Envelope)(nil),            // 2: voiceline.webcall.v1.Envelope
	(*AuthConfirm)(nil),         // 3: voiceline.webcall.v1.AuthConfirm
	(*AuthResult)(nil),          // 4: voiceline.webcall.v1.AuthResult
	(*LineInfo)(nil),            // 5: voiceline.webcall.v1.LineInfo
	(*DialRequest)(nil),         // 6: voiceline.webcall.v1.DialRequest
	(*CallEvent)(nil),           // 7: voiceline.webcall.v1.CallEvent
	(*HangupRequest)(nil),       // 8: voiceline.webcall.v1.HangupRequest
	(*DtmfRequest)(nil),         // 9: voiceline.webcall.v1.DtmfRequest
	(*DtmfEvent)(nil),           // 10: voiceline.webcall.v1.DtmfEvent
	(*MediaStart)(nil),          // 11: voiceline.webcall.v1.MediaStart
	(*AudioFrame)(nil),          // 12: voiceline.webcall.v1.AudioFrame
	(*Ping)(nil),                // 13: voiceline.webcall.v1.Ping
	(*Pong)(nil),                // 14: voiceline.webcall.v1.Pong
	(*TransferRequest)(nil),     // 15: voiceline.webcall.v1.TransferRequest
	(*TransferEvent)(nil),       // 16: voiceline.webcall.v1.TransferEvent
	(*ConferenceInvite)(nil),    // 17: voiceline.webcall.v1.ConferenceInvite
	(*ConferenceEvent)(nil),     // 18: voiceline.webcall.v1.ConferenceEvent
	(*Bye)(nil),                 // 19: voiceline.webcall.v1.Bye
	(*InboundSubscription)(nil), // 20: voiceline.webcall.v1.InboundSubscription
	(*InboundAck)(nil),          // 21: voiceline.webcall.v1.InboundAck
	(*IncomingCallEvent)(nil),   // 22: voiceline.webcall.v1.IncomingCallEvent
	(*AcceptRequest)(nil),       // 23: voiceline.webcall.v1.AcceptRequest
	(*RejectRequest)(nil),       // 24: voiceline.webcall.v1.RejectRequest
}
var file_proto_webcall_proto_depIdxs = []int32{
	3,  // 0: voiceline.webcall.v1.Envelope.auth_confirm:type_name -> voiceline.webcall.v1.AuthConfirm
	4,  // 1: voiceline.webcall.v1.Envelope.auth_result:type_name -> voiceline.webcall.v1.AuthResult
	6,  // 2: voiceline.webcall.v1.Envelope.dial:type_name -> voiceline.webcall.v1.DialRequest
	7,  // 3: voiceline.webcall.v1.Envelope.call_event:type_name -> voiceline.webcall.v1.CallEvent
	8,  // 4: voiceline.webcall.v1.Envelope.hangup:type_name -> voiceline.webcall.v1.HangupRequest
	9,  // 5: voiceline.webcall.v1.Envelope.dtmf:type_name -> voiceline.webcall.v1.DtmfRequest
	10, // 6: voiceline.webcall.v1.Envelope.dtmf_event:type_name -> voiceline.webcall.v1.DtmfEvent
	11, // 7: voiceline.webcall.v1.Envelope.media_start:type_name -> voiceline.webcall.v1.MediaStart
	12, // 8: voiceline.webcall.v1.Envelope.audio:type_name -> voiceline.webcall.v1.AudioFrame
	13, // 9: voiceline.webcall.v1.Envelope.ping:type_name -> voiceline.webcall.v1.Ping
	14, // 10: voiceline.webcall.v1.Envelope.pong:type_name -> voiceline.webcall.v1.Pong
	19, // 11: voiceline.webcall.v1.Envelope.bye:type_name -> voiceline.webcall.v1.Bye
	15, // 12: voiceline.webcall.v1.Envelope.transfer:type_name -> voiceline.webcall.v1.TransferRequest
	16, // 13: voiceline.webcall.v1.Envelope.transfer_ev:type_name -> voiceline.webcall.v1.TransferEvent
	17, // 14: voiceline.webcall.v1.Envelope.conf_invite:type_name -> voiceline.webcall.v1.ConferenceInvite
	18, // 15: voiceline.webcall.v1.Envelope.conf_event:type_name -> voiceline.webcall.v1.ConferenceEvent
	20, // 16: voiceline.webcall.v1.Envelope.inbound_sub:type_name -> voiceline.webcall.v1.InboundSubscription
	21, // 17: voiceline.webcall.v1.Envelope.inbound_ack:type_name -> voiceline.webcall.v1.InboundAck
	22, // 18: voiceline.webcall.v1.Envelope.incoming:type_name -> voiceline.webcall.v1.IncomingCallEvent
	23, // 19: voiceline.webcall.v1.Envelope.accept:type_name -> voiceline.webcall.v1.AcceptRequest
	24, // 20: voiceline.webcall.v1.Envelope.reject:type_name -> voiceline.webcall.v1.RejectRequest
	5,  // 21: voiceline.webcall.v1.AuthResult.line:type_name -> voiceline.webcall.v1.LineInfo
	22, // [22:22] is the sub-list for method output_type
	22, // [22:22] is the sub-list for method input_type
	22, // [22:22] is the sub-list for extension type_name
	22, // [22:22] is the sub-list for extension extendee
	0,  // [0:22] is the sub-list for field type_name
}

func init() { file_proto_webcall_proto_init() }
func file_proto_webcall_proto_init() {
	if File_proto_webcall_proto != nil {
		return
	}
	file_proto_webcall_proto_msgTypes[2].OneofWrappers = []any{
		(*Envelope_AuthConfirm)(nil),
		(*Envelope_AuthResult)(nil),
		(*Envelope_Dial)(nil),
		(*Envelope_CallEvent)(nil),
		(*Envelope_Hangup)(nil),
		(*Envelope_Dtmf)(nil),
		(*Envelope_DtmfEvent)(nil),
		(*Envelope_MediaStart)(nil),
		(*Envelope_Audio)(nil),
		(*Envelope_Ping)(nil),
		(*Envelope_Pong)(nil),
		(*Envelope_Bye)(nil),
		(*Envelope_Transfer)(nil),
		(*Envelope_TransferEv)(nil),
		(*Envelope_ConfInvite)(nil),
		(*Envelope_ConfEvent)(nil),
		(*Envelope_InboundSub)(nil),
		(*Envelope_InboundAck)(nil),
		(*Envelope_Incoming)(nil),
		(*Envelope_Accept)(nil),
		(*Envelope_Reject)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_webcall_proto_rawDesc), len(file_proto_webcall_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   25,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_webcall_proto_goTypes,
		DependencyIndexes: file_proto_webcall_proto_depIdxs,
		MessageInfos:      file_proto_webcall_proto_msgTypes,
	}.Build()
	File_proto_webcall_proto = out.File
	file_proto_webcall_proto_goTypes = nil
	file_proto_webcall_proto_depIdxs = nil
}
